# Generated by Django 5.0.6 on 2024-06-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_producto_remove_itemcarrito_carrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ItemOrden',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
