# Generated by Django 5.0.6 on 2024-06-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('editorial', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('ano_publicacion', models.PositiveIntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('numero_paginas', models.PositiveIntegerField()),
            ],
        ),
    ]
