# Generated by Django 5.0.6 on 2024-06-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_producto_alter_libro_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
