# Generated by Django 5.0.6 on 2024-06-16 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_carrito_creado_en_alter_itemcarrito_cantidad_and_more'),
        ('pedido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='libros',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='items',
            field=models.ManyToManyField(related_name='pedidos', to='carrito.itemcarrito'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
